[package]
name = "jrsonnet"
description = "Rust jsonnet implementation"
version = "0.4.2"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2021"

[features]
experimental = ["exp-preserve-order", "exp-destruct"]
# Use mimalloc as allocator
mimalloc = ["mimallocator"]
# Experimental feature, which allows to preserve order of object fields
exp-preserve-order = [
    "jrsonnet-evaluator/exp-preserve-order",
    "jrsonnet-evaluator/exp-serde-preserve-order",
    "jrsonnet-cli/exp-preserve-order",
]
# Destructuring of locals
exp-destruct = ["jrsonnet-evaluator/exp-destruct"]

[dependencies]
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.4.2" }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.4.2" }
jrsonnet-cli = { path = "../../crates/jrsonnet-cli", version = "0.4.2" }
jrsonnet-gcmodule = { version = "0.3.4" }

mimallocator = { version = "0.1.3", optional = true }
thiserror = "1.0"
clap = { version = "3.1", features = ["derive"] }
clap_complete = { version = "3.1" }
