[package]
name = "jrsonnet-types"
description = "Jrsonnet type system definition"
version = "0.4.2"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2021"

[dependencies]
jrsonnet-gcmodule = { version = "0.3.4" }

peg = "0.8.0"
