[package]
name = "jrsonnet-rowan-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.51"
backtrace = "0.3.63"
drop_bomb = "0.1.5"
indoc = "1.0.3"
logos = "0.12.0"
miette = { version = "4.2.1", features = ["fancy"] }
rowan = "0.15.0"
text-size = "1.1.0"
thiserror = "1.0.30"

[dev-dependencies]
backtrace = "0.3.63"
indoc = "1.0.3"
insta = "1.10.0"
anyhow = "1.0.57"
jrsonnet-stdlib = { path = "../jrsonnet-stdlib" }
